version: "3"

services:
  database:
    build: ./database
    container_name: database
    restart: always
    ports:
      - "3306:3306"

  backend:
    build: ./backend/UserLibrary
    container_name: backend
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - database

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    restart: always
