version: "3"

services:
  database:
    build: ./database
    container_name: database
    restart: always
    ports:
      - "3306:3306"
#    networks:
#      - spring_net

#  backend:
#    build: ./backend/UserLibrary
#   container_name: backend
#    ports:
#      - "8080:8080"
#    restart: always
#    networks:
#      - spring_net
#      - f#rontend_net
#    depends_on:
#      - database

#networks:
#  spring_net:
#  frontend_net:
