CREATE DATABASE UserLibrary;
USE UserLibrary;

CREATE TABLE USERS(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cognome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    p_hash CHAR(60)
);

CREATE TABLE USER_BOOKS(
    ISBN CHAR(13) NOT NULL PRIMARY KEY,
    user_id INT NOT NULL,
    titolo VARCHAR(255) NOT NULL,
    autore VARCHAR(255) NOT NULL,
    add_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    del_date TIMESTAMP DEFAULT NULL,
    trama VARCHAR(255),
    letture INT NOT NULL DEFAULT 0,
    CONSTRAINT user_del FOREIGN KEY (user_id) REFERENCES USERS(id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

